### ISSUE TITLE
Site not compatible with mobile browsers

### ISSUE THREAD

**Issue by herronelou** [cgstudiomap/cgstudiomap#184]
Trying to display the website on mobile browser (Android) is close to un-usable. 
UI elements are out of the screen, the map on the homepage is zoomable, but not really.

**Comment by foutoucour** [comment]
Thank for the report @herronelou 

We didn't make enough effort for the mobile version and we will address it.

@M4rtine could take a look at it?

**Comment by M4rtine** [comment]
Yes

Le jeudi 16 juillet 2015, Jordi Riera <notifications@github.com> a écrit :

> Thank for the report @herronelou <https://github.com/herronelou>
>
> We didn't make enough effort for the mobile version and we will address it.
>
> @M4rtine <https://github.com/M4rtine> could take a look at it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/184#issuecomment-121946681>
> .
>


-- 

____________________________

*david.mazeau*
*06 64 19 11 50www.davidmazeau.com <http://www.davidmazeau.com>*

**Comment by foutoucour** [comment]
Fixed in #200 
Mobile:
![cgstudiomap 2015-07-19 16-29-51_mobile](https://cloud.githubusercontent.com/assets/547282/8767721/a27f75f2-2e33-11e5-8d0e-66fdca545320.png)

Small Tablet:
![cgstudiomap 2015-07-19 16-30-48_smalltablet](https://cloud.githubusercontent.com/assets/547282/8767723/b1e31878-2e33-11e5-80be-c6a5accb36c9.png)

tablet:
![cgstudiomap 2015-07-19 16-30-18_tablet](https://cloud.githubusercontent.com/assets/547282/8767725/b93faabe-2e33-11e5-8278-cc144731f2d7.png)
