### ISSUE TITLE
Access map without login in

### ISSUE THREAD

**Issue by herronelou** [cgstudiomap/cgstudiomap#186]
I tried showing my coworkers the map, which they closed when they realized they had to register in order to see the map, they didn't want to create an account just to consult a map.

**Comment by foutoucour** [comment]
Thanks for the report @herronelou 

The behaviour is currently wanted. The details of companies are only available to our users not to visitors.

I am more concerned by the fact they don't want to create an account. 
Could let me know if they didn't want to because it is too long to create an account? 
Would they have created an account using quick creation through social network?

thank you for feedbacks

**Comment by M4rtine** [comment]
We need people who share datas with other people.
It is not a passive consultation

Le jeudi 16 juillet 2015, Jordi Riera <notifications@github.com> a écrit :

> Thanks for the report @herronelou <https://github.com/herronelou>
>
> The behaviour is currently wanted. The details of companies are only
> available to our users not to visitors.
>
> I am more concerned by the fact they don't want to create an account.
> Could let me know if they didn't want to because it is too long to create
> an account?
> Would they have created an account using quick creation through social
> network?
>
> thank you for feedbacks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/186#issuecomment-121947361>
> .
>


-- 

____________________________

*david.mazeau*
*06 64 19 11 50www.davidmazeau.com <http://www.davidmazeau.com>*

**Comment by MangoJazz** [comment]
today 850 visits and 440 registrations, 50% visits transform to users, I'd say we can keep the sign-up button for now. 
We could re-think the whole sign-up thing if this behaviour changes.
Tx Erwan :)
