### ISSUE TITLE
Signup Popup on home page displays even once logged in

### ISSUE THREAD

**Issue by herronelou** [cgstudiomap/cgstudiomap#187]
Signup Popup on home page displays even once logged in

**Comment by foutoucour** [comment]
Thank you @herronelou 

The bug will be addressed soon.

**Comment by M4rtine** [comment]
I think we must change the  view too.

Replace
"FIND A STUDIO" by "Welcome to CG STUDIO MAP"

Delete
"Welcome to cgstudiomap"

Replace
"SIGNUP" by "FIND A STUDIO"



Le jeudi 16 juillet 2015, Jordi Riera <notifications@github.com> a écrit :

> Thank you @herronelou <https://github.com/herronelou>
>
> The bug will be addressed soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/187#issuecomment-121947463>
> .
>


-- 

____________________________

*david.mazeau*
*06 64 19 11 50www.davidmazeau.com <http://www.davidmazeau.com>*

**Comment by foutoucour** [comment]
It might be a good idea but it is too early to change the text. I want to
give more time to the text to see its impact.

The issue should stay focused on the display of the popup if the user is
logged or not.

On Thu, Jul 16, 2015 at 8:58 AM David Mazeau <notifications@github.com>
wrote:

> I think we must change the view too.
>
> Replace
> "FIND A STUDIO" by "Welcome to CG STUDIO MAP"
>
> Delete
> "Welcome to cgstudiomap"
>
> Replace
> "SIGNUP" by "FIND A STUDIO"
>
>
>
> Le jeudi 16 juillet 2015, Jordi Riera <notifications@github.com> a écrit :
>
> > Thank you @herronelou <https://github.com/herronelou>
> >
> > The bug will be addressed soon.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/cgstudiomap/cgstudiomap/issues/187#issuecomment-121947463
> >
> > .
> >
>
>
> --
>
> ____________________________
>
> *david.mazeau*
> *06 64 19 11 50www.davidmazeau.com <http://www.davidmazeau.com>*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/187#issuecomment-121949063>
> .
>
-- 
---
- Jordi Riera, Connecting Softwares and people.
Founder at www.cgstudiomap.org, Because everyone should be familiar with
the cg industry

www.linkedin.com/in/jordirieracg/ <http://ca.linkedin.com/in/jordirieracg/>

**Comment by foutoucour** [comment]
fixed by 77a2a38
