### ISSUE TITLE
Re-think the "completely free forever"

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#206]
I am afraid that it could be a fake advertising, we might have legal troubles, once it will be $, maybe re-think the whole sentence for 
"Sign-Up for Free"

Your thoughts?

**Comment by foutoucour** [comment]
I see your concerned. It will be addressed in the next release. It is the
same message but less ambiguous.

On Sun, Jul 19, 2015, 4:12 PM MangoJazz <notifications@github.com> wrote:

> I am afraid that it could be a fake advertising, we might have legal
> troubles, once it will be $, maybe re-think the whole sentence for
> "Sign-Up for Free"
>
> Your thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/206>.
>
-- 
---
- Jordi Riera, Connecting Softwares and people.
Founder at www.cgstudiomap.org, Because everyone should be familiar with
the cg industry

www.linkedin.com/in/jordirieracg/ <http://ca.linkedin.com/in/jordirieracg/>

**Comment by MangoJazz** [comment]
So I have asked my coworkers about it and they advised me that the sentence "It is Free" should be underneath on the left side of the "Sign-up button" in lower case.

example:

SIGN-UP
        It's free

**Comment by M4rtine** [comment]
Do you think it's the same if i put this mention under "SIGN UP" but in the
button.
In ergonomics, action ending is better when the last bloc is the button.



--

**Comment by MangoJazz** [comment]
yes perfect, the purpose of this, is to make sure it is clear that sgning-up is free not the whole website.

**Comment by MangoJazz** [comment]
it looks good, thank you David :)
