### ISSUE TITLE
Change cg Studio Map in front page

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#225]
Please change cgstudiomap to cg Studio Map in the front page, I am not able to do it :(.

Cheers

**Comment by foutoucour** [comment]
On Sun, Jul 26, 2015 at 6:35 PM MangoJazz <notifications@github.com> wrote:

> Assigned #225 <https://github.com/cgstudiomap/cgstudiomap/issues/225> to
> @foutoucour <https://github.com/foutoucour>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/225#event-365612152>.
>
-- 
---
- Jordi Riera, Connecting Softwares and people.
Founder at www.cgstudiomap.org, Because everyone should be familiar with
the cg industry

www.linkedin.com/in/jordirieracg/ <http://ca.linkedin.com/in/jordirieracg/>

**Comment by foutoucour** [comment]
done in #226
