### ISSUE TITLE
Bootlint tool

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#242]
http://www.bootlint.com/
check bootstrap validator and create issues for optimisation.

**Comment by foutoucour** [comment]
Interesting indeed

On Tue, Aug 4, 2015 at 7:56 AM David Mazeau <notifications@github.com>
wrote:

> http://www.bootlint.com/
> check bootstrap validator and create issues for optimisation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/242>.
>
-- 
---
- Jordi Riera, Connecting Softwares and people.
Founder at www.cgstudiomap.org, Because everyone should be familiar with
the cg industry

www.linkedin.com/in/jordirieracg/ <http://ca.linkedin.com/in/jordirieracg/>

**Comment by M4rtine** [comment]
HOMEPAGE
[ ] Missing DOCTYPE
[ ] Simplified col-XX grid classes. it's redundant.
[ ] Check : "Line 291, Column 29: Columns (`.col-*-*`) can only be children of `.row`s"

**Comment by foutoucour** [comment]
I checked the homepage. no failure. Need to keep this tool somewhere. Quite useful.
