### ISSUE TITLE
About section

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#269]
In the about section could you please add 2 sections?
At the present we have the contact us section.

- History 
- The team (picture & description)

Thanks

**Comment by M4rtine** [comment]
description pour la Team
on met une phrase ou plutôt un poste de travail ?

**Comment by MangoJazz** [comment]
Je vote pour une phrase.

**Comment by foutoucour** [comment]
Une phrase aussi serait plus interessant. Un poste de travail serait trop
limitatif je dirai.

On Wed, Dec 16, 2015 at 7:13 AM MangoJazz <notifications@github.com> wrote:

> Je vote pour une phrase.
> Le 2015-12-16 3:30 AM, "David Mazeau" <notifications@github.com> a écrit :
>
> > description pour la Team
> > on met une phrase ou plutôt un poste de travail ?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/cgstudiomap/cgstudiomap/issues/269#issuecomment-165030866
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/269#issuecomment-165088866>
> .
>
-- 
---
- Jordi Riera, Connecting Softwares and people.
Founder at www.cgstudiomap.org, Because everyone should be familiar with
the cg industry

www.linkedin.com/in/jordirieracg/ <http://ca.linkedin.com/in/jordirieracg/>
