### ISSUE TITLE
Verify account society6

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#291]
https://society6.com/account/earnings

"In order to sell your artwork as prints or other products you must be a verified member of Society6, this is how we pay you for your sales"

**Comment by foutoucour** [comment]
"""Congratulations! You've successfully completed Society6 ID verification.
You can now sell your artwork on Society6 and apply for any Collaboration
and sell your artwork on Society6 without having to repeat this process
again. There will also be an icon on your profile showing that you are a
verified user.

Remember, this is also the same PayPal account that will be used to send
you earnings from sales or collaborations.

Post Products! <https://society6.com/post>

"""


good to go!

On Sun, Nov 8, 2015 at 9:00 AM David Mazeau <notifications@github.com>
wrote:

> https://society6.com/account/earnings
>
> "In order to sell your artwork as prints or other products you must be a
> verified member of Society6, this is how we pay you for your sales"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/291>.
>
-- 
---
- Jordi Riera, Connecting Softwares and people.
Founder at www.cgstudiomap.org, Because everyone should be familiar with
the cg industry

www.linkedin.com/in/jordirieracg/ <http://ca.linkedin.com/in/jordirieracg/>
