### ISSUE TITLE
Goodies on the website

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#302]
Could you please add the link for the goodies on the main page of cgstudiomap.org?

Many thanks

**Comment by MangoJazz** [comment]
here is the link for the code
https://society6.com/account/banner

**Comment by M4rtine** [comment]
waiting for a better web integration too
 i think the quickest method is a "SHOP" word in navbar

**Comment by foutoucour** [comment]
implementation of the link to our society6

![6_20151115_001](https://cloud.githubusercontent.com/assets/547282/11169929/57e47f84-8b93-11e5-9d6f-9360c6c3cd06.png)

**Comment by foutoucour** [comment]
A page has been set www.cgstudiomap.org/shop that redirect to our shop.

Double aim with this page:
* track the traffic to the shop: we should advertise www.cgstudiomap.org/shop instead of the the url of society6. So analytics will track the traffic to society6.
* manage the direction to the shop: if we move away from society6 to another website, we keep the same url.

**Comment by MangoJazz** [comment]
Thank you :)
