### ISSUE TITLE
Design for Xmas cards

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#317]
David, would you have time to design some arts for the wishes cards?

**Comment by M4rtine** [comment]
What is the support ?
- PRINT :
   * business card, postal card, double opened card ?
model choice : http://www.vistaprint.fr/carte-de-voeux.aspx?txi=17049&xnid=TopNav_Holiday+Cards+(linked+item)_Cards+%26+Invites&xnav=TopNav

- WEB :
    * newsletter, in website ?

we need : 
- the logo
- catchphrase
- Xmas reference minimalist design (ex: snow...)
- personalize sentence in order to say that studios are in database but in more talked about
( "you're in" "you're company is in" ...)
- wishes sentence
("happy CG wishes")

**Comment by MangoJazz** [comment]
Je t"envoie un email.

**Comment by MangoJazz** [comment]
merge #352
