### ISSUE TITLE
Home Page/Directory same page

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#336]
La page d'accueil est la seule page qu'on peut voir. En cliquant sur les autres icones on retombe sur la home page.

**Comment by MangoJazz** [comment]
@foutoucour il semblerait que le probleme soit résolu. Depuis le taff j'ai accès au directory. ouff. Ce que tu as fait ce matin fonctionne.

**Comment by foutoucour** [comment]
c'est un hotfix que j'ai fait, mais la source du probleme n'est pas regle encore :(

**Comment by MangoJazz** [comment]
ok, j'ai renvoyé le lien à image in network et ça à l'air de fonctionner maintenant. Merci d'avoir temporairement fixé le pb.

**Comment by foutoucour** [comment]
cool que ca marche pour le gars :)

Je reglerai mieux ca ce WE

On Fri, Dec 4, 2015 at 9:38 AM MangoJazz <notifications@github.com> wrote:

> ok, j'ai renvoyé le lien à image in network et ça à l'air de fonctionner
> maintenant. Merci d'avoir temporairement fixé le pb.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/336#issuecomment-161982256>
> .
>
-- 
---
- Jordi Riera, Connecting Softwares and people.
Founder at www.cgstudiomap.org, Because everyone should be familiar with
the cg industry

www.linkedin.com/in/jordirieracg/ <http://ca.linkedin.com/in/jordirieracg/>
