### ISSUE TITLE
UK studios enhancement

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#359]

**Comment by MangoJazz** [comment]
154 à ajouter le logo + verification adresse

**Comment by MangoJazz** [comment]
En cours, plus que 123 :(

**Comment by MangoJazz** [comment]
finis youyou

**Comment by foutoucour** [comment]
GG!

On Tue, Dec 29, 2015 at 2:03 PM MangoJazz <notifications@github.com> wrote:

> finis youyou
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/359#issuecomment-167854022>
> .
>
-- 
---
- Jordi Riera, Connecting Softwares and people.
Founder at www.cgstudiomap.org, Because everyone should be familiar with
the cg industry

www.linkedin.com/in/jordirieracg/ <http://ca.linkedin.com/in/jordirieracg/>
