### ISSUE TITLE
Mise à jour studios USA

### ISSUE THREAD

**Issue by MangoJazz** [cgstudiomap/cgstudiomap#409]

**Comment by MangoJazz** [comment]
336 to go

**Comment by MangoJazz** [comment]
yesssss terminé

**Comment by foutoucour** [comment]
super bravo!

On Sat, Jan 16, 2016 at 8:51 PM MangoJazz <notifications@github.com> wrote:

> Closed #409 <https://github.com/cgstudiomap/cgstudiomap/issues/409>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/409#event-517133401>.
>
-- 
---
- Jordi Riera, Connecting Softwares and people.
Founder at www.cgstudiomap.org, Because everyone should be familiar with
the cg industry

www.linkedin.com/in/jordirieracg/ <http://ca.linkedin.com/in/jordirieracg/>
