### ISSUE TITLE
Design Navigation DIRECTORY

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#439]

**Comment by M4rtine** [comment]
@foutoucour  Question je connais pas bien les INPUT.
Pour le switch map/list j'ai besoin d'un icone au lieu du wording.

Pourquoi quand j'écris ça j'ai les deux : 
```
<input type='submit' t-att-class="'btn btn-default a-submit' if (url == list_url) else 'btn btn-default disabled' " value="map">
<i class="fa fa-th-list fa-2x"></i>
</input>
```

**Comment by foutoucour** [comment]
c'est le parametre value="map" qui met le nom sur le bouton.

pour mettre un icone sur un bouton submit, ca l'air un peu galere:
http://jsfiddle.net/Abdull/MhNjL/

Mais c'est faisable : )

On Tue, Jan 12, 2016 at 8:31 AM David Mazeau <notifications@github.com>
wrote:

> @foutoucour <https://github.com/foutoucour> Question je connais pas bien
> les INPUT.
> Pour le switch map/list j'ai besoin d'un icone au lieu du wording.
>
> Pourquoi quand j'écris ça j'ai les deux :
>
> <input type='submit' t-att-class="'btn btn-default a-submit' if (url == list_url) else 'btn btn-default disabled' " value="map">
> <i class="fa fa-th-list fa-2x"></i>
> </input>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/439#issuecomment-170912430>
> .
>
-- 
---
- Jordi Riera, Connecting Softwares and people.
Founder at www.cgstudiomap.org, Because everyone should be familiar with
the cg industry

www.linkedin.com/in/jordirieracg/ <http://ca.linkedin.com/in/jordirieracg/>

**Comment by M4rtine** [comment]
Super, nan c'est facile en fait c'est de l'unicode avec fontawesome

On pourra avoir mieux quand on aura notre propre typo. Il suffira d'écrire le mot pour qu'il remplace par l'icone. (ligatures)

**Comment by M4rtine** [comment]
XML & Unicode :

"&#x10FFFD;" = wrong
"U+10FFFD" = good
