### ISSUE TITLE
Studio details condition

### ISSUE THREAD

**Issue by M4rtine** [cgstudiomap/cgstudiomap#526]
Faire les conditions d'apparitions des détails du studio.
Mettre le placeholder pour donner envie de remplir avec le lien vers l'édition ou un quick edition.

**Comment by M4rtine** [comment]
En attente du pull request de # 514 dans 
la branch "frontend_studio"

**Comment by foutoucour** [comment]
mis en place pour les champs:
* website
* email
* industry_ids
* social networks
* phone
* mobile
* fax


![uploads/039e9374-1353-4598-ba4f-48e65fd31fab/1_20160128_001.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F039e9374-1353-4598-ba4f-48e65fd31fab%2F1_20160128_001.png)

**Comment by foutoucour** [comment]
Je veux retravailler les social networks pour que qu'un seul `+` n'apparaisse.

**Comment by M4rtine** [comment]
cool cest ce que je pensais j'imaginais aussi qu'il en yé qu'un seul

--

**Comment by M4rtine** [comment]
le + doit être après les icones sociaux valides

**Comment by foutoucour** [comment]
oui c'est ce qui est prevu :)

Est ce que l'ordre des boutons doit toujours etre le meme?
genre
1 - twitter
2 - youtube
3 - ...

ou l'ordre n'est pas important?

On Fri, Jan 29, 2016 at 5:23 AM David Mazeau <notifications@github.com>
wrote:

> le + doit être après les icones sociaux valides
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/526#issuecomment-176682551>
> .
>
-- 
---
- Jordi Riera, Connecting Softwares and people.
Founder at www.cgstudiomap.org, Because everyone should be familiar with
the cg industry

www.linkedin.com/in/jordirieracg/ <http://ca.linkedin.com/in/jordirieracg/>

**Comment by M4rtine** [comment]
L'ordre n'a pas d'importance selon mon avis. 

Tu es au courant que l'on peut pas rajouter des liens sociaux dans "Additional Socials network"
message d'erreur

**Comment by foutoucour** [comment]
oui ca sera fait dans #524
